apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cg-myapp
  name: cg-myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cg-myapp
  template:
    metadata:
      labels:
        app: cg-myapp
    spec:
      containers:
      - name: my-cg-myapp
        image: 
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
          name: http
          protocol: TCP
#Service Type Loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: cg-myapp
    k8s-app: cg-myapp
  name: cg-myapp
spec:
  selector:
    app: cg-myapp
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: Loadbalancer
