apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cgtest0301
    name: cgtest03dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cgtest0301
  template:
    metadata:
      labels:
        app: cgtest0301
    spec:
      containers:
      - name: cgtest03cont
        image: 35.74.253.177:8083/springapp
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
#Service Type LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: cgtest0301
    k8s-app: cgtest0301
  name: cgtest03svc
spec:
  selector:
    app: cgtest0301
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: Loadbalancer
